pipeline{
    agent any
    environment {
    PATH = "/opt/maven/bin:$PATH"
    }
        stages{
        
        stage('Build'){
            steps{
                echo 'Building Okay..'
                sh "whoami"
                sh "echo $PATH"
                sh 'mvn -f demo/pom.xml clean package -X'
                /*sh "docker build . -t demo:${env.BUILD_ID}"*/
                sh "docker build . -f demo/Dockerfile -t demo:${env.BUILD_ID}"
            }
        }
    
    stage('Sonarqube') {
    						environment {
       							 scannerHome = tool 'localSonar'
   								 		}
    					steps {
        						withSonarQubeEnv('aws_sonarqube') {
            					sh "${scannerHome}/sonar-scanner"
       											 }
       							 timeout(time: 10, unit: 'MINUTES') {
            					waitForQualityGate abortPipeline: true
        					}
   						 }
}
    
    
    
		}

		post {
      			always {
        			junit '**/target/surefire-reports/*.xml'
      				}
      		 }


}