pipeline{
    agent any
    environment {
    PATH = "/opt/sonar/bin:/opt/maven/bin:$PATH"
    registryCredential = 'gcr:demoecrid'
    ECRURL ='https://358493496165.dkr.ecr.ap-southeast-1.amazonaws.com/uploadfille'
    }
        stages{
        
        stage('Build'){
            steps{
                echo 'Building Okay..'
                sh "whoami"
                sh "echo $PATH"
                
                //cleanup current user docker credentials
       			 sh 'rm  ~/.dockercfg || true'
       			 sh 'rm ~/.docker/config.json || true'
                
                
                //echo 'Workspace is..'
                //sh  "echo $WORKSPACE"
                sh 'mvn -f demo/pom.xml clean package -X'
                /*sh "docker build . -t demo:${env.BUILD_ID}"*/
                sh "docker build . -f demo/Dockerfile -t demo:${env.BUILD_ID}"
            }
        }
    
    stage('Docker Push'){
     steps{
    			//sh "docker.withRegistry('https://358493496165.dkr.ecr.ap-southeast-1.amazonaws.com/uploadfille', 'ecr:us-east-1:demoecrid') {docker.image('demo').push('latest')"
    
         script {
         
          //docker.withRegistry('https://358493496165.dkr.ecr.ap-southeast-1.amazonaws.com/uploadfille', 'ecr:demoecrid') {docker.image('demo').push('latest')}
          //docker.withRegistry('https://358493496165.dkr.ecr.ap-southeast-1.amazonaws.com/uploadfille', registryCredential) {docker.image('demo').push('latest')}
          //
          //docker.withRegistry('https://358493496165.dkr.ecr.ap-southeast-1.amazonaws.com/uploadfille', 'ecr:ap-southeast-1:demoecrid') {docker.image('demo').push('latest')}
         
          docker.withRegistry(ECRURL,registryCredential)
           {
                        docker.image('demo').push()
            }
         
         }
    
    	}
    
    }
    
    
    
    //
    /*** start only if needed due to cost
    stage('Sonarqube') {
    						environment {
       							 scannerHome = tool 'localSonar'
   								 		}
    					steps {
        						withSonarQubeEnv('aws_sonarqube') {
            					sh "${scannerHome}/sonar-scanner"
       											 }
       							 timeout(time: 10, unit: 'MINUTES') {
            					waitForQualityGate abortPipeline: true
        					}
   						 }
}
    **/
    //
    
    
		}

		post {
      			always {
        			junit '**/target/surefire-reports/*.xml'
      				}
      		 }


}