pipeline{
    agent any
    environment {
    PATH = "/opt/maven/bin:$PATH"
    }
        stages{
        stage('Build'){
            steps{
                echo 'Building Okay..'
                sh "whoami"
                sh "echo $PATH"
                sh 'mvn -f demo/pom.xml clean package -X'
                /*sh "docker build . -t demo:${env.BUILD_ID}"*/
                sh "docker build -f demo/Dockerfile -t demo:${env.BUILD_ID}
            }
        }
    }
}